sudo: required

lanquage: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t baeseokin/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true baeseokin/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"